services:
  admin:
    image: ghcr.io/timeleaplabs/tlp-admin:1.0.2
    env_file: .env
    container_name: tlp-admin
    restart: unless-stopped
    expose:
      - "${ADMIN_SUBNET_PORT}"
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
